### ISSUE TITLE
Add Order property to ShowOnDashboardAttribute

### ISSUE THREAD

**Issue by SoftAdviceJR** [M-Files/VAF.Extensions.Community#102]
Add an Order property (int) to the ShowOnDashboardAttribute so that the order in which the Task Processors are returned by GetAsynchronousOperationDashboardContent can be controlled easily

**Comment by CraigHawker** [comment]
This is an excellent suggestion.  Processors are currently returned [here](https://github.com/M-Files/VAF.Extensions.Community/blob/master/MFiles.VAF.Extensions/Dashboards/AsynchronousDashboardContent/TaskManagerExAsynchronousDashboardContentProvider.cs#L64), so the logic on retrieving queues and processors would need to be altered such that the attribute is available and is used to order the processors before they're returned.

**Comment by CraigHawker** [comment]
Thank you to @SoftAdviceJR for the PR; merged!
