### ISSUE TITLE
[Security(IsPassword = true)] issue

### ISSUE THREAD

**Issue by cv3tko** [M-Files/VAF.Extensions.Community#119]
If Security flag with IsPassword = true is set, after changing the configuration sometimes the value gets corrupted.
Use case:
SQL connection string is set and masked with [Security(IsPassword = true)]. If configuration is changed without setting the connection string freshly every time, the connection string gets corrupted. Users report the error "Format of the initialization string does not conform to specification starting at index 0." from UI. When overwriting the value of connection string, the correct value is saved once again.
Extensions 23.7.58

**Comment by CraigHawker** [comment]
Are you using this within a list, something like the below:

```csharp
[DataContract]
public class Configuration : ConfigurationBase
{
[DataMember]
public List<MyItem> X { get;set;} = new List<MyItem>();
}
[DataContract]
public class MyItem
{
[DataMember]
[Security(IsPassword=true)]
public string ConnectionString {get;set;}
}
```

If so then you could be running into [this issue](https://community.m-files.com/groups-1602070992/developers/f/developer-forum/7612/security-for-password-nvm/22891#22891).

The solution is to make sure that "MyItem" extends [ConfigurationCollectionItemBase](https://github.com/M-Files/VAF.Extensions.Community/blob/119f52680194e32f1d5d6a665b9ed1de24c3de48/MFiles.VAF.Extensions/Configuration/ConfigurationCollectionItemBase.cs):

```csharp
[DataContract]
public class Configuration : ConfigurationBase
{
[DataMember]
public List<MyItem> X { get;set;} = new List<MyItem>();
}
[DataContract]
public class MyItem : ConfigurationCollectionItemBase
{
[DataMember]
[Security(IsPassword=true)]
public string ConnectionString {get;set;}
}
```

If this doesn't resolve the issue then please do update the issue with steps on how to replicate the problem and I will look into it.

**Comment by cv3tko** [comment]
Yes, the connection string is used within a list. I extended the class with ConfigurationCollectionItemBase and could not reproduce the issue for now, so I think that solved it.
Thank you for the quick reply.

**Comment by CraigHawker** [comment]
Awesome.  I'll close the issue and see whether I can add some supporting documentation around this.  As you can see: it doesn't come up frequently, but it's come up once or twice so it's worth trying to note somewhere.
