### ISSUE TITLE
I would like an easy way to trigger a recurring background operation from M-Files Admin

### ISSUE THREAD

**Issue by aaron-hardin** [M-Files/VAF.Extensions.Community#14]
Would be nice to have a button in the dashboard that I can click to trigger the operation...but without having to code each individual background operation into the dashboard.

**Comment by CraigHawker** [comment]
Really nice idea.  Approach from @aaron-hardin's pull request has been pulled into the https://github.com/M-Files/VAF.Extensions.Community/tree/show-run-command-on-dashboard branch.

Pre-release `1.2.4-background-tasks-on-schedule` and higher includes this functionality.

Documentation to be updated in that branch.

**Comment by CraigHawker** [comment]
Example of using the `ShowRunCommandOnDashboard` attribute has been added to this sample: https://github.com/M-Files/VAF.Extensions.Community/tree/show-run-command-on-dashboard/MFiles.VAF.Extensions/MultiServerMode/TaskQueueBackgroundOperationManager#allowing-the-user-to-run-the-background-operation-via-the-dashboard

```
public class VaultApplication
	: MFiles.VAF.Extensions.ConfigurableVaultApplicationBase<Configuration>
{
	/// <summary>
	/// The background operation that can be run on demand.
	/// The ShowRunCommandOnDashboard attribute adds the "Run now" button next to the
	/// background operation in the list on the dashboard.  No other changes are required.
	/// </summary>
	[ShowRunCommandOnDashboard]
	protected TaskQueueBackgroundOperation MyBackgroundOperation { get; private set; }

	/// <inheritdoc />
	protected override void StartApplication()
	{
		try
		{
			// Create a background operation that can be run on demand.
			this.MyBackgroundOperation = this.TaskQueueBackgroundOperationManager.CreateBackgroundOperation
			(
				"My on-demand background operation",
				(job) =>
				{
					SysUtils.ReportInfoToEventLog("I have been run on demand.");
				}
			);
		}
		catch(Exception e)
		{
			SysUtils.ReportErrorToEventLog("Exception starting background operations", e);
		}
	}

}
```
