### ISSUE TITLE
Using scheduled background job to start UserGroup syncronization

### ISSUE THREAD

**Issue by kappas** [M-Files/VAF.Extensions.Community#39]
I've been looking for a way make own interval for User Group synchronization in M-Files. Basic functionality as described in here [Importing User Groups](https://www.m-files.com/user-guide/2018/eng/Import_user_groups.html) suggests that interval is hard coded 15 minutes and cannot be changed.

However when looking at this [Creating a background operation that runs on a schedule](https://github.com/M-Files/VAF.Extensions.Community/tree/master/MFiles.VAF.Extensions/TaskQueueBackgroundOperations/TaskQueueBackgroundOperationManager#creating-a-background-operation-that-runs-on-a-schedule) , it seems like a perfect place to issue such a command at wanted interval.

Only one unknown factor is that I'm not sure if its possible to command Vault to start synchronizing UserGroup from Active Directory via any API. 

Any help would be appreciated.

Br,
Kappas

**Comment by CraigHawker** [comment]
Hi,

Please don't open issues on this library for questions on the M-Files API.

For more general support requests you have three options:
1. Contact your reseller or Channel Account Manager.
2. Contact support@m-files.com.  Note that scripting requests fall outside of our standard support, so you may be passed to your reseller, or provided with additional support options.
3. Post a question on the M-Files Community (https://community.m-files.com/forums-1552881334/).

That said, I don't believe that the AD sync can be stared via our API, so I don't think that this will be an option unfortunately.

Regards,

Craig.

**Comment by kappas** [comment]
Cheers for the tips and sorry for posting issue not related directly to this library.

**Comment by CraigHawker** [comment]
No worries - have a great day!
