### ISSUE TITLE
Add MFSearchBuilder.IsPropertyEmpty and MFSearchBuilder.IsPropertyNotEmpty extension methods

### ISSUE THREAD

**Issue by CraigHawker** [M-Files/VAF.Extensions.Community#4]
The current methods for searching for objects with an empty property (or, conversely, a property with any value) are cumbersome.  These involve searching for where a property equals or does not equal null and require the provision of the property type at compile time.

Suggested to add methods such as:
`public static MFSearchBuilder IsPropertyEmpty(this MFSearchBuilder searchBuilder, int propertyId);`

This method should use the existing vault reference to get the data type of the property and call the existing method to add a search condition to find objects where the property is equal to null.

The same should be done for IsPropertyNotEmpty, but searching for objects where the property is not equal to null.

**Comment by falk-huth-ewerk** [comment]
Sounds good.

Is there also a method for IsPropertySet – also on ObjVerEx?


__

Falk Huth
Product Owner ECM/DMS Practice

EWERK DIGITAL GmbH
Brühl 24, D-04109 Leipzig
P +49 341 42649 - 514
F +49 341 42649 - 98
M +49 151 53984493
F.Huth@ewerk.com
www.ewerk.com

Geschäftsführer:
Dr. Erik Wende, Hendrik Schubert, Tassilo Möschke
Registergericht: Leipzig HRB 9065

Support:
+49 341 42649 555

Zertifiziert nach:
ISO/IEC 27001:2013
DIN EN ISO 9001:2015
DIN ISO/IEC 20000-1:2011

ISAE 3402 Typ II Assessed

EWERK-Blog<https://blog.ewerk.com/> | LinkedIn<https://www.linkedin.com/company/ewerk-group> | Xing<https://www.xing.com/company/ewerk> | Twitter<https://twitter.com/EWERK_Group> | Facebook<https://de-de.facebook.com/EWERK.IT/>


Auskünfte und Angebote per Mail sind freibleibend und unverbindlich.

Disclaimer Privacy:
Der Inhalt dieser E-Mail (einschließlich etwaiger beigefügter Dateien) ist vertraulich und nur für den Empfänger bestimmt. Sollten Sie nicht der bestimmungsgemäße Empfänger sein, ist Ihnen jegliche Offenlegung, Vervielfältigung, Weitergabe oder Nutzung des Inhalts untersagt. Bitte informieren Sie in diesem Fall unverzüglich den Absender und löschen Sie die E-Mail (einschließlich etwaiger beigefügter Dateien) von Ihrem System. Vielen Dank.

The contents of this e-mail (including any attachments) are confidential and may be legally privileged. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system. Thank you.
Von: Craig Hawker <notifications@github.com>
Gesendet: Montag, 7. September 2020 12:47
An: M-Files/VAF.Extensions.Community <VAF.Extensions.Community@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [M-Files/VAF.Extensions.Community] Add MFSearchBuilder.IsPropertyEmpty and MFSearchBuilder.IsPropertyNotEmpty extension methods (#4)


The current methods for searching for objects with an empty property (or, conversely, a property with any value) are cumbersome. These involve searching for where a property equals or does not equal null and require the provision of the property type at compile time.

Suggested to add methods such as:
public static MFSearchBuilder IsPropertyEmpty(this MFSearchBuilder, int propertyId);

This method should use the existing vault reference to get the data type of the property and call the existing method to add a search condition to find objects where the property is equal to null.

The same should be done for IsPropertyNotEmpty, but searching for objects where the property is not equal to null.

**Comment by CraigHawker** [comment]
Hi Falk,

There is a `[HasValue](https://developer.m-files.com/Frameworks/Vault-Application-Framework/Helpers/ObjVerEx/#property-helper-methods)` method on `ObjVerEx` already, if you have loaded your object and need to see whether one specific object contains a property, and that property is not empty.

Regards,

Craig.

**Comment by CraigHawker** [comment]
Naming of these extension methods is open for discussion.  `Is` may be a bad prefix in this context.

**Comment by CraigHawker** [comment]
Methods PropertyEmpty and PropertyNotEmpty added in commit bf2dd1830d7b9669d509508cfc2ff1acb9822853.

Will be in the next public release.
