### ISSUE TITLE
Add MFSearchBuilder.Owner extension method

### ISSUE THREAD

**Issue by CraigHawker** [M-Files/VAF.Extensions.Community#5]
Extension method should be implemented as overrides that take:

- ObjID owner
- ObjVer owner

Testing should be added to ensure that the method adds the correct search condition:

- Load the parent ObjType and find the owner property def.
- Add a search condition where the owner property def (above) equals the object ID of the provided owner.

**Comment by falk-huth-ewerk** [comment]
Below you find some sample code for a use case where I export master data - so ObjVerEx would be a good parameter, too:


            // Get the owner Mandant propertyDef
            ObjType owningObjType = env.Vault.ObjectTypeOperations.GetObjectType(Configuration.Identifier.ObjectType.Mandant);
            int besitzerMandant = owningObjType.OwnerPropertyDef;

            // search Mandant -> Lieferanten
            sb = new MFSearchBuilder(env.Vault);
            sb.ObjType(Configuration.Identifier.ObjectType.Mandant);
            sb.Property(Configuration.Identifier.PropertyDef.IstBebuchbar, MFDataType.MFDatatypeBoolean, true);
            sb.Deleted(false);
            List<ObjVerEx> mandanten = sb.FindEx();
            foreach (ObjVerEx mandant in mandanten)
            {
                string mandantNummer = mandant.GetPropertyText(Configuration.Identifier.PropertyDef.NummerMandant);
                string mandantKuerzel = mandant.GetPropertyText(Configuration.Identifier.PropertyDef.KuerzelMandant);
                filename = exportDir + mandantNummer + "_" + mandantKuerzel + "_" + LIEFERANTEN;
                File.WriteAllText(filename, "ID;Name;Erstellung;Änderung\n");

                sb = new MFSearchBuilder(env.Vault);
                sb.ObjType(Configuration.Identifier.ObjectType.Lieferant);
                sb.Property(besitzerMandant, MFDataType.MFDatatypeLookup, mandant.ID);
                sb.Deleted(false);
                entries = sb.FindEx(sort: true);
                foreach (ObjVerEx entry in entries)
                {
                    nummer = entry.Info.DisplayID;
                    File.AppendAllText(filename, string.Format(
                        "{0};{1};{2};{3}\n",
                        nummer,
                        entry.Title,
                        entry.GetPropertyText(MFBuiltInPropertyDef.MFBuiltInPropertyDefCreated),
                        entry.GetPropertyText(MFBuiltInPropertyDef.MFBuiltInPropertyDefLastModified)));
                }
            }

**Comment by CraigHawker** [comment]
Initial implementation complete with tests and merged to master.
