### ISSUE TITLE
Creating new custom directive, which would contain other fields than object related field

### ISSUE THREAD

**Issue by esahaapamaki** [M-Files/VAF.Extensions.Community#54]
Currently VAF.Extensions has ObjVerExTaskDirective and ObjIDTaskDirective directives. It would be nice to have also one custom directive which would contain other fields as well. The custom directive could contain ObjID and List<ObjID> fields and additionally couple int, double and string fields. This way we would have one pre-built custom directive with methods validating are the fields filled or not. This way there wouldn't be a need to create custom directives for every case.

**Comment by doze** [comment]
Please check pull request for this: https://github.com/M-Files/VAF.Extensions.Community/pull/55

**Comment by CraigHawker** [comment]
Merged PR #55 which contains an example of this, so closing.  Thank you all!
