### ISSUE TITLE
Error in base.GetDashboardContent when missing ShowOnDashboardAttribute

### ISSUE THREAD

**Issue by SoftAdviceJR** [M-Files/VAF.Extensions.Community#62]
When leaving off the ShowOnDashboard attribute from a TaskProcessor I'm getting a null reference error in base.GetDashboardContent.

I don't think that the ShowOnDashboard attribute should be mandatory, right?

**Comment by CraigHawker** [comment]
That's correct; that's definitely a bug.  I'll get that resolved immediately.

**Comment by CraigHawker** [comment]
This is fixed in `22.5.26`, which is going through publishing now.
