### ISSUE TITLE
Escape XML in Task Update message

### ISSUE THREAD

**Issue by SoftAdviceJR** [M-Files/VAF.Extensions.Community#63]
So, I might have accidentally put some XML in my job.Update() message and now the entire dashboard won't render:

MyApp: [System.Collections.Generic.List`1[TSource] ToList[TSource](System.Collections.Generic.IEnumerable`1[TSource])], IL:20, Input string was not in a correct format. (0x80131537)
MyApp: [Void .ctor(System.Collections.Generic.IEnumerable`1[T])], IL:119, Input string was not in a correct format. (0x80131537)
MyApp: [Boolean MoveNext()], IL:1232, Input string was not in a correct format. (0x80131537)
MyApp: [MFiles.VAF.Configuration.Domain.Dashboards.IDashboardContent AsDashboardContent[TDirective](System.Collections.Generic.IEnumerable`1[MFiles.VAF.AppTasks.TaskInfo`1[TDirective]], Int32)], IL:1519, Input string was not in a correct format. (0x80131537)
MyApp: [MFiles.VAF.Configuration.Domain.Dashboards.IDashboardContent AsDashboardContent(Boolean)], IL:245, Input string was not in a correct format. (0x80131537)
MyApp: [System.String EscapeXmlForDashboard(System.String)], IL:0, Input string was not in a correct format. (0x80131537)
MyApp: [System.String Format(System.String, System.Object[])], IL:24, Input string was not in a correct format. (0x80131537)
MyApp: [System.String FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)], IL:14, Input string was not in a correct format. (0x80131537)
MyApp: [System.Text.StringBuilder AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)], IL:0, Input string was not in a correct format. (0x80131537)
MyApp: [Void FormatError()], IL:15, Input string was not in a correct format. (0x80131537)
(M-Files 22.4.11321.4 2022-05-03T10:52:44.698Z)

**Comment by CraigHawker** [comment]
Do you have an idea of the sort of XML you added?  I can definitely add a unit test for this and get it fixed in the next release.  In the interim you may need to wait for that task to drop out of the list of jobs that are returned for rendering on the dashboard.

Alternatively, depending what's in the queue right now, change the task queue ID in your code so that you're not attempting to render that older queue with the job that's causing the problem.

**Comment by CraigHawker** [comment]
Having just tested this, I can render out some XML.  Do you know what value you provided?
![image](https://user-images.githubusercontent.com/6346782/166442665-f5d73ede-8ee9-41f0-927f-a753e773f988.png)

**Comment by SoftAdviceJR** [comment]
I'll send you an email since this contains some confidential info

**Comment by CraigHawker** [comment]
This should be fixed in `22.5.27`.  Please re-open this issue if it does not solve the problem.
