### ISSUE TITLE
Functionality to check the latest logs from dashboard

### ISSUE THREAD

**Issue by esahaapamaki** [M-Files/VAF.Extensions.Community#64]
With the logging framework and VAF.Extensions, there is now a possibility to download log files via M-Files Admin. That is awesome feature.

Sometimes there is a need just to check what were the latest couple log lines. It would be beneficial if there wouldn't be a requirement to download the log set to own computer, extracting the files and finding the correct log. 

New functionality could be to have the latest logs visible in the dashboard or to add View button which opens popup window and shows the latest logs.

**Comment by CraigHawker** [comment]
This is now in `22.6.31`.
