### ISSUE TITLE
Add a configuration option to use UTC in the Schedule time triggers

### ISSUE THREAD

**Issue by KatriinaHalonen** [M-Files/VAF.Extensions.Community#66]
Currently, the times configured in the Schedule class for recurring tasks are interpreted as server local time. In cloud installations, the server time zone may not be known to admins doing the configuration. Therefore, a possibility to define the schedule as UTC time would be a nice option to give a better control for the scheduled tasks.

**Comment by CraigHawker** [comment]
This functionality is being explored in branch https://github.com/M-Files/VAF.Extensions.Community/tree/allow-schedules-in-different-timezones

An initial preview release is available in https://www.nuget.org/packages/MFiles.VAF.Extensions/22.8.0.18-allow-schedules-in-different-timezones.

Work still to do:

 * Additional unit tests?
 * Labels for configuration elements into resource files
 * Labels for time zone stuff into resource files

**Comment by CraigHawker** [comment]
Labels added to resource files in e16f92494e0a9b9c3e353bb40a80dba1e085d443.

**Comment by CraigHawker** [comment]
Implemented in https://github.com/M-Files/VAF.Extensions.Community/commit/77dd461e7e75782aa8bb55199e97cf6c9bd892b3.  Closing.
