### ISSUE TITLE
Create extension methods for dashboard generation

### ISSUE THREAD

**Issue by CraigHawker** [M-Files/VAF.Extensions.Community#7]
Creating nice-looking dashboard is awkward.  Extension/helper methods for dashboard generation would be a nice way to create uniformity in applications.

**Comment by CraigHawker** [comment]
Some helpers starting to be created in https://github.com/M-Files/VAF.Extensions.Community/tree/master/MFiles.VAF.Extensions/Dashboards, e.g.:

* [DashboardProgressBar](https://github.com/M-Files/VAF.Extensions.Community/blob/master/MFiles.VAF.Extensions/Dashboards/DashboardProgressBar.cs)
* [DashboardTable](https://github.com/M-Files/VAF.Extensions.Community/blob/master/MFiles.VAF.Extensions/Dashboards/DashboardTable.cs)

**Comment by falk-huth-ewerk** [comment]
![image](https://user-images.githubusercontent.com/63024286/152079227-6fc54417-fd25-48cb-8735-b49d464cc16a.png)

Something like that? Did I send you already the e-mail with the base structure of it?

**Comment by CraigHawker** [comment]
The creation of consistent dashboards is not easy to do using the current VAF helpers.  This boils down to two things, really:
1.  There is little guidance on how the various existing classes and helper methods should be used, and existing (widely-used) VAF applications often extend these classes and helper methods adding in their own custom CSS on top of whatever is produced automatically.  External developers don't necessarily have visibility of this so it's very difficult to replicate.
2. There is no easy-to-use toolkit of dashboard UI elements that would make it easy for developers to create dashboards that look and feel like official M-Files applications without having to concern themselves with the above.

Creating nice-looking dashboards is possible (I've seen some beautiful ones), and the utilisation of a module structure is sometimes part of that concept, but the issue is more broad than provision of code.

To move this forward I think we need a wider discussion on:
- What dashboards people have created themselves already, and what we (as a community) feel are good implementations from either a UI or UX perspective.
- What UI components may be needed (e.g. table) for developers to easily and quickly create dashboards that are consistent and usable.

From that conversation we can start to then look at designing a way forward.

**Comment by CraigHawker** [comment]
Closing the issue as the deliverable here is not specific (how would we ever be able to mark this as complete?).
