### ISSUE TITLE
Cannot get rid of TaskQueueBackgroundOperation

### ISSUE THREAD

**Issue by Ezeckiel2517** [M-Files/VAF.Extensions.Community#75]
I recently upgrade to VAF 2.3 and extension from 1.2 to latest 22.9.
I really love the new task architecture and the new dashboard.

One thing I noted after I completed the migration to task is that there is still an old background task running even after I removed all the old boilerplate code. This is a minor concern but I rather not have it running when not needed.

After some research it appears that the background operations is created when I consult the dashboard. In fact, GetAsynchronousOperationDashboardContent method use reflection that will trigger the TaskQueueBackgroundOperationManager property getter on the vault app and start it.

**Comment by CraigHawker** [comment]
When you say that it's still running, how are you seeing this?  Are you using the old TaskQueueBackgroundOperationManager at all?  Did you change the queue and task ID when you updated, or could it be using the same one (I doubt this, but...)?

The reason I ask is that if you are no longer registering a background operation with TaskQueueBackgroundOperationManager then I'm unsure what exactly it would try to run; there's no user code associated with it at all, and no knowledge of an interval.

FYI: The next version of the VAF will bring some breaking changes, and I am minded to remove the TaskQueueBackgroundOperationManager in its entirety.  It was really designed as a sticking plaster to help people move from the old background operation approach to task queues, back when task queues were difficult to use.  Now that's not the case, there's little use for it, and it's just something else to maintain.

**Comment by Ezeckiel2517** [comment]
I do not use the old TaskQueueBackgroundOperationManager anymore. What I did is to open the vault database and look into the table APPLICATIONTASKQUEUE. Because I have changed all my queueId to use a naming with "." instead of "-" I see there was still 1 called "xyz-BackgroundOperations". This is the old naming from the TaskQueueBackgroundOperationManager.

I also did delete all those rows from the table (I know I should not do this but it is a dev vault) and restart the vault.
At first thoses queues were not there anymore but when I check the dashboard in the admin they get back. That was the hint it have something to do with the dashboard.

**Comment by CraigHawker** [comment]
Aha.

Obviously, firstly: don't muck about in the database. 😉

In this case what's happening is that the queue is being registered.  It's not actually queuing and running things.  If you have nothing registered with the TaskQueueBackgroundOperationManager then no tasks will ever actually be placed into its queue.

It's a side-effect of the dashboard rendering, but it has no overhead and there are no knock-on effects of this happening.  If you aren't looking in the database then you wouldn't even see the registration.

As I said: this is something that we'll probably guide people away from soon, at which point this will also stop happening.

**Comment by Ezeckiel2517** [comment]
Also I use the extension unit test to validate.
```
	[TestClass]
	public class ConfigurableVaultApplicationBaseTests
		: TestBaseWithVaultMock
	{
		[TestMethod]
		public void DashboardContentTest()
		{
			var contextMoq = new Mock<IConfigurationRequestContext>();
			var application = new ConfigurableVaultApplicationBaseProxy();
			application.GetAsynchronousOperationDashboardContent(contextMoq.Object);
		}
	}
```
And it goes inside this
```
		protected TaskQueueBackgroundOperationManager<TSecureConfiguration> TaskQueueBackgroundOperationManager
		{
			get
			{
				if (null != this.taskQueueBackgroundOperationManager)
					return this.taskQueueBackgroundOperationManager;
				lock (this._lock)
				{
					try
					{
						taskQueueBackgroundOperationManager =
							taskQueueBackgroundOperationManager ?? new TaskQueueBackgroundOperationManager<TSecureConfiguration>(this);
					}
					catch
					{
						// This may except if the vault is not yet started.
						// Allow it to return null.
					}
					return taskQueueBackgroundOperationManager;
				}
			}
			private set => taskQueueBackgroundOperationManager = value;
		}
	}
```

**Comment by Ezeckiel2517** [comment]
Great it is fine for me if it will be removed eventually.
