### ISSUE TITLE
Feature request: extend ShowOnDashboardAttribute with configurable command

### ISSUE THREAD

**Issue by aaron-hardin** [M-Files/VAF.Extensions.Community#98]
Currently 'ShowRunCommand' is a bool and it will just add a task, it would be nice to have [string RunCommandId]

- if string.IsNullOrWhitespace( RunCommandId ) -> default behavior
- else -> instead of adding a task, run the domain command

This would enable running a specific command rather than just adding a task.

**Comment by CraigHawker** [comment]
This is included in 23.4.50.
